// NextJs
import Head from "next/head";
import type { NextPage } from "next";

import { Text } from "@geist-ui/react";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" type="image/png" href="/ethiopic.png" />
      </Head>

      <Text h1>Hello, World</Text>
    </div>
  );
};

export default Home;
