// NextJs
import Head from "next/head";
import type { NextPage } from "next";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Ethiopian StartUps</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" type="image/png" href="/ethiopic.png" />
      </Head>

      <h1>Hello</h1>
    </div>
  );
};

export default Home;
